
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto.pkg1.compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int especialC = 6;
  public static final int comma = 2;
  public static final int cadena = 5;
  public static final int entero = 4;
  public static final int error = 1;
  public static final int identificador = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "comma",
  "identificador",
  "entero",
  "cadena",
  "especialC"
  };
}

